# Generated by Django 5.0.4 on 2024-04-28 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animais', models.BooleanField()),
                ('dataDeCriacao', models.DateTimeField(auto_now_add=True)),
                ('codigoPostal', models.CharField(max_length=8)),
                ('morada', models.CharField(max_length=400)),
                ('numQuartos', models.PositiveSmallIntegerField()),
                ('area', models.FloatField()),
                ('anoConstrucao', models.PositiveSmallIntegerField()),
                ('mobilada', models.BooleanField()),
                ('negociavel', models.BooleanField()),
                ('descricao', models.TextField()),
                ('numWCs', models.PositiveSmallIntegerField()),
                ('classeEnergetica', models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'A'), (3, 'B'), (4, 'B-'), (5, 'C'), (6, 'D'), (7, 'E')])),
                ('titulo', models.CharField(max_length=300)),
                ('highlighted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=400, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveSmallIntegerField()),
                ('estadoCivil', models.PositiveSmallIntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Viúvo'), (4, 'Divorciado'), (5, 'Separado judicialmente de pessoas e bens')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgenteImobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=400, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveSmallIntegerField()),
                ('estadoCivil', models.PositiveSmallIntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Viúvo'), (4, 'Divorciado'), (5, 'Separado judicialmente de pessoas e bens')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=400, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveSmallIntegerField()),
                ('estadoCivil', models.PositiveSmallIntegerField(choices=[(1, 'Solteiro'), (2, 'Casado'), (3, 'Viúvo'), (4, 'Divorciado'), (5, 'Separado judicialmente de pessoas e bens')])),
                ('animais', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
