# Generated by Django 5.0.2 on 2024-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0003_remove_admin_email_remove_agenteimobiliario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='animais',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telemovel',
            field=models.PositiveIntegerField(),
        ),
    ]
