# Generated by Django 5.0.2 on 2024-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0004_alter_cliente_animais_alter_cliente_telemovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telemovel',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
