# Generated by Django 5.0.2 on 2024-05-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0006_cliente_urlprofilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='cidade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Grande Lisboa'), (1, 'Grande Porto'), (2, 'Aveiro'), (3, 'Braga'), (4, 'Coimbra'), (5, 'Faro'), (6, 'Funchal'), (7, 'Guimarães'), (8, 'Ponta Delgada'), (9, 'Póvoa de Varzim'), (10, 'Viana do Castelo'), (11, 'Vila Franca de Xira'), (12, 'Viseu')], default=0),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
