# Generated by Django 4.2.13 on 2024-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0010_alter_pedidoscriacaoanuncio_tratado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='salvos',
            field=models.ManyToManyField(related_name='props_salvas', to='romax.propriedade'),
        ),
    ]
