# Generated by Django 4.2.13 on 2024-05-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0011_alter_cliente_salvos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='subtipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Studio'), (1, 'T1'), (2, 'T2'), (3, 'T3+'), (4, 'Duplex'), (5, 'Triplex'), (6, 'Penthouse'), (7, 'Térrea'), (8, 'Vila'), (9, 'Campo')]),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Apartamento'), (1, 'Moradia'), (2, 'Outro')]),
        ),
    ]
