# Generated by Django 4.2.13 on 2024-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0013_alter_propriedade_subtipo_alter_propriedade_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='classeEnergetica',
            field=models.PositiveSmallIntegerField(choices=[(0, 'A+'), (1, 'A'), (2, 'B'), (3, 'B-'), (4, 'C'), (5, 'D'), (6, 'E')]),
        ),
    ]
