# Generated by Django 5.0.4 on 2024-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0014_alter_propriedade_classeenergetica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoscriacaoanuncio',
            name='data_fecho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='titulo',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
