# Generated by Django 4.2.13 on 2024-05-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0016_alter_pedidoscriacaoanuncio_tratado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='dono',
            field=models.ForeignKey(blank=True, null=True,on_delete=django.db.models.deletion.CASCADE, to='romax.cliente'),
        ),
    ]
