# Generated by Django 4.2.13 on 2024-05-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romax', '0021_alter_propriedade_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=320)),
                ('com', models.TextField()),
            ],
        ),
    ]
